### ISSUE TITLE
FSNS demo

### ISSUE THREAD

**Issue by sne21star** [Bartzi/see#103]
When preparing the dataset for the FSNS demo it says to run this command: python swap_classes.py <gt_file> <output_file_name> 0 133. What exactly is the gt_file?

**Comment by Bartzi** [comment]
For the demo, you do not need to do this.
However, if you try to prepare data for training, you'll need to do this. `gt_file` refers to the file that is produced by the script `tfrecord_to_image.py`

**Comment by sne21star** [comment]
Yes I was able to get that part working thank you. Also did you ever get this error before and know how to solve it? 
Traceback (most recent call last):
  File "/content/drive/My Drive/Colab Notebooks/see/chainer/train_fsns.py", line 169, in <module>
    updater = MultiprocessParallelUpdater(train_iterators, optimizer, devices=args.gpus)
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 145, in __init__
    assert len(iterators) == len(devices)
AssertionError


Sorry I think I fixed that ^ error with using standardupdater but now I can't seem it run it 
   updater = StandardUpdater(train_iterators, optimizer, device=args.gpus) when I changed the multiprocessor to this line.  

This is also the command line that I am using: 

!python /content/drive/My\ Drive/Colab\ Notebooks/see/chainer/train_fsns.py      /content/drive/My\ Drive/Colab\ Notebooks/see/fsns_labels/curriculum.json        /content/drive/My\ Drive/Colab\ Notebooks/see/fsns_labels    --char-map /content/drive/My\ Drive/Colab\ Notebooks/see/datasets/fsns/fsns_char_map.json.   --blank-label 0     -b 2     --gpu 0

**Comment by Bartzi** [comment]
okay, what is your new error? Is it the one in the other issue?
