### ISSUE TITLE
fsns_demo problem

### ISSUE THREAD

**Issue by BouafifOussema** [Bartzi/see#3]
Hi, 
i find a problem when i want to use fsns_demo , here is the code : 

python3 fsns_demo.py /home/mcq-2/projects/see/datasets/ /home/mcq-2/projects/see/chainer/models/model_35000.npz /home/mcq-2/projects/see/chainer/models/tag.jpg /home/mcq-2/projects/see/datasets/fsns/fsns_char_map.json 

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "fsns_demo.py", line 153, in <module>
    chainer.serializers.NpzDeserializer(f).load(network)
  File "/usr/local/lib/python3.5/dist-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/usr/local/lib/python3.5/dist-packages/chainer/link.py", line 795, in serialize
    d[name].serialize(serializer[name])
  File "/home/mcq-2/projects/see/datasets/ic_stn.py", line 125, in serialize
    super().serialize(serializer)
  File "/usr/local/lib/python3.5/dist-packages/chainer/link.py", line 795, in serialize
    d[name].serialize(serializer[name])
  File "/usr/local/lib/python3.5/dist-packages/chainer/link.py", line 551, in serialize
    data = serializer(name, param.data)
  File "/usr/local/lib/python3.5/dist-packages/chainer/serializers/npz.py", line 115, in __call__
    dataset = self.npz[key]
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'localization_net/conv0_1/W is not a file in the archive'

Can you help me please ? 

Thanks

**Comment by Bartzi** [comment]
You are using the script in the wrong way:
it should be 

python3 fsns_demo.py **/home/mcq-2/projects/see/datasets/models model_35000.npz** /home/mcq-2/projects/see/chainer/models/tag.jpg /home/mcq-2/projects/see/datasets/fsns/fsns_char_map.json

**Comment by BouafifOussema** [comment]
Thank you very much for your response,

Can you explain to me how can i do to train a new model for text recognition using the "Synthetic Word Dataset". I have download images but i don't know how to do to prepare the annotation file
there is only txt files.

Thank you,
