### ISSUE TITLE
pretrain_model error

### ISSUE THREAD

**Issue by zhikangD** [Bartzi/see#4]
Hi, I'm running the demo code but get error like:
python3 ./chainer/fsns_demo.py ./datasets/models/ model_35000.npz ./datasets/testimg/4.png ./datasets/svhn/svhn_char_map.json
Traceback (most recent call last):
  File "./chainer/fsns_demo.py", line 153, in <module>
    predictions, crops, grids = network(image[xp.newaxis, ...])
  File "/home/ubuntu/see/datasets/models/fsns.py", line 516, in __call__
    images = F.reshape(images, (batch_size, num_channels, height, 4, -1))
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/array/reshape.py", line 98, in reshape
    y, = Reshape(shape).apply((x,))
  File "/usr/local/lib/python3.5/dist-packages/chainer/function_node.py", line 230, in apply
    self._check_data_type_forward(in_data)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function_node.py", line 298, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/array/reshape.py", line 40, in check_type_forward
    type_check.prod(x_type.shape) % size_var == 0)
  File "/usr/local/lib/python3.5/dist-packages/chainer/utils/type_check.py", line 524, in expect
    expr.expect()
  File "/usr/local/lib/python3.5/dist-packages/chainer/utils/type_check.py", line 482, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType:
Invalid operation is performed in: Reshape (Forward)

Expect: prod(in_types[0].shape) % known_size(=600) == 0
Actual: 450 != 0
can't really figure out which part cause that issue

**Comment by Bartzi** [comment]
Yes, the input image needs to have the correct size.
If you have a look at the original `FSNS` samples, you can see that there are always 4 views in one sample. The expected input size for the `FSNS` model is `600x150`

You are also using the wrong `char_map` for `FSNS` it has to be `fsns_char_map.json` from the `fsns` folder in the `datasets` folders. The file `svhn_char_map.json` does not include the correct mapping of labels to class

**Comment by zhikangD** [comment]
Thanks for the reply, Is the model_35000.npz also compatible with svhn model? The model I'm trying to test is actually digit recognition.

**Comment by Bartzi** [comment]
Hmm, I would say it is not really compatible. Depends on your samples. If you only want to do digit recognition on already cropped house numbers, you should have a look at the text recognition model.

If you also want to do digit localization on full sized SVHN images, you might need to train yourself a model. But that depends on your images, I also do have some SVHN models, that I did not yet upload. I could upload them if needed, but I can't do that before next week.
So what kind of samples are you experimenting on?

**Comment by zhikangD** [comment]
I'm testing on some already cropped images with both text and digits, it's like marathon bibs with text at first row and digits at second. Digits are the first thing I want from there. For the text, it's good to be detected, but it's fine if not. I'm trying to test some pretrained model before I come up with my own, and it's challenging because the bibs are usually twisted or photos are took from different angles.

**Comment by Bartzi** [comment]
Alright, then I suggest, that you use the text recognition model and the `text_recognition_demo.py` script. You can try whether this model already helps you with your task. If not it might be beneficial to do a retraining
