### ISSUE TITLE
Failed on load weights file for custom train data set

### ISSUE THREAD

**Issue by rezha130** [Bartzi/see#44]
Hi @Bartzi 

I already successfully train my custom data set, then i copy all result files from log to `mytrain` folder. But when i try the result model with this command:

`python text_recognition_demo.py mytrain model_42000.npz mytrain/00001.jpg mytrain/ctc_char_map.json --gpu 0`

that command failed on on load weights file
```
File "text_recognition_demo.py", line 158, in <module>
    chainer.serializers.NpzDeserializer(f).load(network)
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/link.py", line 954, in serialize
    d[name].serialize(serializer[name])
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/link.py", line 954, in serialize
    d[name].serialize(serializer[name])
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/link.py", line 612, in serialize
    data = serializer(name, param.data)
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/serializers/npz.py", line 151, in __call__
    value.set(numpy.asarray(dataset, dtype=value.dtype))
  File "cupy/core/core.pyx", line 1696, in cupy.core.core.ndarray.set
  File "cupy/core/core.pyx", line 1712, in cupy.core.core.ndarray.set
ValueError: Shape mismatch. Old shape: (52,), new shape: (72,)
```

Please help.

**Comment by mit456** [comment]
Just a check, Your test image shape is same as training images?

**Comment by rezha130** [comment]
![ea58338c-1f3b-4a91-ba49-0817ff74e785](https://user-images.githubusercontent.com/39994669/42014975-5015f9a8-7acf-11e8-960d-757f9e0db9c5.png)


above is a sample of my train image..and this is a sample from my ground truth file with tab delimited

15	16
`mytrain/image/00001.jpg 	Alamat	:	CLUSTER	WATER	GARDEN	BH.10/27	GRAND	WISATA	`

15 is maximum word per image from my custom train set
16 is maximum character per word from my custom train set too

CMIIW if my ground truth file is not correct yet

**Comment by Bartzi** [comment]
@rezha130 I think your problem is [this](https://github.com/Bartzi/see/blob/master/chainer/text_recognition_demo.py#L45) line, you should exchange `52` by `72`. You char_map is different to the one I've been using. This problem could be fixed in the same way as done with PR #41.

**Comment by rezha130** [comment]
@Bartzi you are an angel! i missed that line..
thanks for kindly reply

**Comment by rezha130** [comment]
@Bartzi thanks for quick reply, now i can test my model result. But another problem appear:

`python text_recognition_demo.py mytrain model_42000.npz mytrain/image/00001.jpg mytrain/ctc_char_map.json --gpu 0`

give this result : 
```
OrderedDict([('Alamat',
              [OrderedDict([('top_left', (10.153651237487793, 0.0)),
                            ('bottom_right', (188.42269897460938, 64.0))]),
               OrderedDict([('top_left', (9.257012367248535, 0.0)),
                            ('bottom_right', (188.95077514648438, 64.0))]),
               OrderedDict([('top_left', (9.751701354980469, 0.0)),
                            ('bottom_right', (189.06959533691406, 64.0))]),
               OrderedDict([('top_left', (16.02237892150879, 0.0)),
                            ('bottom_right', (188.70294189453125, 64.0))]),
               OrderedDict([('top_left', (23.43842315673828, 0.0)),
                            ('bottom_right', (188.17893981933594, 64.0))]),
               OrderedDict([('top_left', (30.188858032226562, 0.0)),
                            ('bottom_right', (187.6661376953125, 64.0))]),
               OrderedDict([('top_left', (35.84349822998047, 0.0)),
                            ('bottom_right', (187.2195281982422, 64.0))]),
               OrderedDict([('top_left', (40.32756805419922, 0.0)),
                            ('bottom_right', (186.85638427734375, 64.0))]),
               OrderedDict([('top_left', (43.758575439453125, 0.0)),
                            ('bottom_right', (186.5736083984375, 64.0))]),
               OrderedDict([('top_left', (46.3254280090332, 0.0)),
                            ('bottom_right', (186.35931396484375, 64.0))]),
               OrderedDict([('top_left', (48.2197265625, 0.0)),
                            ('bottom_right', (186.19967651367188, 64.0))]),
               OrderedDict([('top_left', (49.60652542114258, 0.0)),
                            ('bottom_right', (186.08200073242188, 64.0))]),
               OrderedDict([('top_left', (50.614906311035156, 0.0)),
                            ('bottom_right', (185.99632263183594, 64.0))]),
               OrderedDict([('top_left', (51.347171783447266, 0.0)),
                            ('bottom_right', (185.93399047851562, 64.0))]),
               OrderedDict([('top_left', (51.879066467285156, 0.0)),
                            ('bottom_right', (185.8885955810547, 64.0))])])])
```

I expect have more words rather than first word..please check my sample of ground truth file on my comment above, is it correct?

**Comment by rezha130** [comment]
@Bartzi  thanks for quick reply, now i can test my model result. 

But another problem appear:

`python text_recognition_demo.py mytrain model_42000.npz mytrain/image/00001.jpg mytrain/ctc_char_map.json --gpu 0`

give this result :

```
OrderedDict([('Alamat',
              [OrderedDict([('top_left', (10.153651237487793, 0.0)),
                            ('bottom_right', (188.42269897460938, 64.0))]),
               OrderedDict([('top_left', (9.257012367248535, 0.0)),
                            ('bottom_right', (188.95077514648438, 64.0))]),
               OrderedDict([('top_left', (9.751701354980469, 0.0)),
                            ('bottom_right', (189.06959533691406, 64.0))]),
               OrderedDict([('top_left', (16.02237892150879, 0.0)),
                            ('bottom_right', (188.70294189453125, 64.0))]),
               OrderedDict([('top_left', (23.43842315673828, 0.0)),
                            ('bottom_right', (188.17893981933594, 64.0))]),
               OrderedDict([('top_left', (30.188858032226562, 0.0)),
                            ('bottom_right', (187.6661376953125, 64.0))]),
               OrderedDict([('top_left', (35.84349822998047, 0.0)),
                            ('bottom_right', (187.2195281982422, 64.0))]),
               OrderedDict([('top_left', (40.32756805419922, 0.0)),
                            ('bottom_right', (186.85638427734375, 64.0))]),
               OrderedDict([('top_left', (43.758575439453125, 0.0)),
                            ('bottom_right', (186.5736083984375, 64.0))]),
               OrderedDict([('top_left', (46.3254280090332, 0.0)),
                            ('bottom_right', (186.35931396484375, 64.0))]),
               OrderedDict([('top_left', (48.2197265625, 0.0)),
                            ('bottom_right', (186.19967651367188, 64.0))]),
               OrderedDict([('top_left', (49.60652542114258, 0.0)),
                            ('bottom_right', (186.08200073242188, 64.0))]),
               OrderedDict([('top_left', (50.614906311035156, 0.0)),
                            ('bottom_right', (185.99632263183594, 64.0))]),
               OrderedDict([('top_left', (51.347171783447266, 0.0)),
                            ('bottom_right', (185.93399047851562, 64.0))]),
               OrderedDict([('top_left', (51.879066467285156, 0.0)),
                            ('bottom_right', (185.8885955810547, 64.0))])])])
```
I expect have more words rather than first word..please check my sample of ground truth file on my comment above, is it correct?

**Comment by Bartzi** [comment]
Did you check those 2 lines? And adjust them to your case?

- [https://github.com/Bartzi/see/blob/master/chainer/text_recognition_demo.py#L142](https://github.com/Bartzi/see/blob/master/chainer/text_recognition_demo.py#L142)
- [https://github.com/Bartzi/see/blob/master/chainer/text_recognition_demo.py#L144](https://github.com/Bartzi/see/blob/master/chainer/text_recognition_demo.py#L144)

**Comment by rezha130** [comment]
@Bartzi i don't missed those 2 lines:

```
# max number of text regions in the image
args.timesteps = 15
# max number of characters per word
args.num_labels = 16
```

for this image:

![ea58338c-1f3b-4a91-ba49-0817ff74e785](https://user-images.githubusercontent.com/39994669/42014975-5015f9a8-7acf-11e8-960d-757f9e0db9c5.png)

This is a sample from my ground truth file with tab delimited for that image

```
15	16
mytrain/image/00001.jpg 	Alamat	:	CLUSTER	WATER	GARDEN	BH.10/27	GRAND	WISATA	
```

15 is maximum word per image from my custom train set
16 is maximum character per word from my custom train set too

Please advice if my ground truth file is not correct yet

**Comment by Bartzi** [comment]
Your groundtruth is not necessary for using the demo script, but it looks okay to me.

Your problem is that you are using a script that is designed for printing only one word.
I'm not 100% sure but I think that [this](https://github.com/Bartzi/see/blob/master/chainer/text_recognition_demo.py#L179) line, could be the solution. Remove the `[0]`.

**Comment by rezha130** [comment]
I removed [0] and get this error:

```
Traceback (most recent call last):
  File "text_recognition_ktp.py", line 181, in <module>
    word = "".join(map(lambda x: chr(char_map[str(x)]), word))
  File "text_recognition_ktp.py", line 181, in <lambda>
    word = "".join(map(lambda x: chr(char_map[str(x)]), word))
KeyError: '[33 28 30]'
```

**Comment by mit456** [comment]
@Bartzi Can we create word based ground thuth file? As @rezha130 has mentioned, till now I have been following the csv structure data, is not that the only way for showing ground thruth to the network?

@rezha130 I am really confused, can you tell me the step you followed to build your custom dataset? would be very grateful

**Comment by Bartzi** [comment]
If you use `train_text_recognition` you can use word based ground truth file... oops yeah that is a little different to the other scripts... hmm I'm sorry for that...

**Comment by rezha130** [comment]
Hi @mit456 and @Bartzi 

Now i try to train with time_step = 72 and max_char = 1 since my max length chars of my train data set is 72 characters (with white space and some special characters).

Please check my python script for creating my ground truth file & ctc_map_char:

```
import sqlite3
import os
import json

from collections import OrderedDict

#gt_word.csv
sqlite_db = 'traindata.db'
conn = sqlite3.connect(sqlite_db)
cursor = conn.cursor()

sql = "select image_name, label from traindata"

result = cursor.execute(sql)

train_dir = "/home/rezha/see/chainer/mytrain"
file_path = "gt_word.csv"

if os.path.exists(file_path):
	os.remove(file_path)

file = open(file_path,'a+') 
max_bound_box = "72"
max_chars = "1"
file.write(max_bound_box + "\t" + max_chars + "\n")

for row in result:
    image_name = row[0]
    label = row[1]
    file.write(os.path.join(train_dir,image_name)+"\t"+ label +"\n") 
conn.close()
file.close()

#ctc_char_map.json
json_path= "ctc_char_map.json"

if os.path.exists(json_path):
	os.remove(json_path)

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz: ()[];&+-/'.,0123456789"
mapping = OrderedDict({"0": 9250})
for idx, char_ in enumerate(sorted(alphabet)):
    mapping[str(idx+1)] = ord(char_)
file = open(json_path,'w+') 
file.write(json.dumps(mapping, sort_keys=False, indent=4))
file.close()
```

**Comment by Bartzi** [comment]
>I remove [0] and get this error:

>Traceback (most recent call last):
  File "text_recognition_demo.py", line 181, in <module>
    word = "".join(map(lambda x: chr(char_map[str(x)]), word))
  File "text_recognition_ktp.py", line 181, in <lambda>
    word = "".join(map(lambda x: chr(char_map[str(x)]), word))
KeyError: '[33 28 30]'

You did expect this, didn't you? Once you remove `[0]` you of course will get an iterable where there was none before... so you'll need to add a loop to the code.

**Comment by rezha130** [comment]
Yes @Bartzi, you're right. But i'm pretty sure that model only predict the first word only and neglect all next sequence words (word based gt & tab delimited). It can be shown on rendered bbox images in log/boxes folder, the result is just first word.

Since you said that `train_text_recognition` script is designed for recognize only one word, so i try to adjust my custom ground truth files & train approaches with that constraint. Now, rendered bbox images show that model learnt to read all defined characters in image --fyi, first word is like title for specific data values..so model can predict it easily--, but it looks line train process need longer epochs to improve. I can wait for that, since loss score tend to decrease slowly..

**Comment by Bartzi** [comment]
First thing I see is that the predicted bboxes don't look good at all.
They should change positions after a while see the text recognition video from [this](https://bartzi.de/documents/attachment/download?hash_value=35314d0f836cc38d8bb64a46663a06e2_7) file.

Furthermore, did you have a close look at the implementation of the dataset loader ([here](https://github.com/Bartzi/see/blob/master/chainer/datasets/file_dataset.py#L99))?
Delimiting with `tab` does not make sense. Sorry, if I misunderstood one of your posts regarding the layout of your groundtruth file.

If you struggle with the groundtruth format, you can also create your own dataset loader!
The only thing you need to make sure is that it returns the right data and is a subclass of the `DatasetMixin`.
The expected return value is a tuple with the loaded image and the label converted from characters to classes, using the char_map. Remember to pad each word according to your maximum of characters per word.

**Comment by rezha130** [comment]
OK @Bartzi . I think my ground truth file still not correct yet for multi words detector after i check `TextRecFileDataset`.

Can you please send example of  ground truth file that you use for the videos, exspecially ground truth files that you used in Text Recognition.mp4 (one word) and FSNS.mp4 (max two words)

Thank you

**Comment by Bartzi** [comment]
okay,

1. `TextRecFileDataset` is not used for training FSNS data.
2. here are the first to lines of the text recognition gt_file:
```
23	1
/data/text_recognition/samples/9999/9999026_]kinkiness_-5_DonegalOne-Regular.jpeg	]kinkiness
```
3. here is an FSNS example for training on 3 text regions
```
3       21
/mnt/ssd/christian/data/fsns/images/train/00000/0.png   67      12      11      1       5       26      20      21      23      0       0       0       0       0       0       0       0       0       0       0        0       23      5       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0              0       0       0       73      11      7       5       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
```

You should have a look at the FSNS examples, `train_text_recognition` does some things differently!

**Comment by rezha130** [comment]
Hi @Bartzi 

Bow i train with train_fsns.py but i got this error

ValueError: all the input array dimensions except for the concatenation axis must match exactly

What does it means?

**Comment by Bartzi** [comment]
hmm, hard to say without the stack trace.

But it basically says, that there are some arrays that are concatenated that do not have the correct shape. Could be because of your input data. Did you make sure to input an image that has this dimensions: `600x150`?

**Comment by rezha130** [comment]
Hi @Bartzi 

Input image size is not fixed in train data set. I am using same images data set when `train using text_recognition` which didn't result this kind of error message.

This is my ground truth file

```
2	16
mytrain/images/0001.jpg	13	11	12	0	0	0	0	0	0	0	0	0	0	0	0	0	4	2	8	3	1	4	7	4	1	3	9	10	1	1	1	7
```

i train with this command

```
python train_fsns.py curriculum.json log \
--blank-label 0 \
--batch-size 32 \
--is-trainer-snapshot \
--use-dropout \
--char-map char_map_nik.json \
--gpu 0 \
--snapshot-interval 1000 \
--dropout-ratio 0.2 \
--epoch 100 
```

please check full stack trace of error below:

```
/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py:150: UserWarning: optimizer.eps is changed to 1e-08 by MultiprocessParallelUpdater for new batch size.
  format(optimizer.eps))
Exception in main training loop: all the input array dimensions except for the concatenation axis must match exactly
Traceback (most recent call last):
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 229, in update_core
    batch = self.converter(batch, self._devices[0])
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/dataset/convert.py", line 133, in concat_examples
    [example[i] for example in batch], padding[i])))
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/dataset/convert.py", line 163, in _concat_arrays
    return xp.concatenate([array[None] for array in arrays])
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train_fsns.py", line 292, in <module>
    trainer.run()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 229, in update_core
    batch = self.converter(batch, self._devices[0])
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/dataset/convert.py", line 133, in concat_examples
    [example[i] for example in batch], padding[i])))
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/dataset/convert.py", line 163, in _concat_arrays
    return xp.concatenate([array[None] for array in arrays])
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by Bartzi** [comment]
> Input images size is not fixed in train data set.
That does not work, because the network is not fully convolutional. It worked with `train_text_recogntion.py` because there the input images are resized prior to being fed to the network.

The FSNS network expects the images to be of shape `600x150` if that is not the shape your data has, you have to adjust the data loading code (and also the network, as your data is likely to be very different to the original FSNS dataset)!

**Comment by rezha130** [comment]
Ok @Bartzi 
Where can i add some code to resized input images to `600x150` for FSNS?

**Comment by rezha130** [comment]
Ok @Bartzi you're right. I resized all my train images to `600x150`.

But now i got this error in `calc_loss` :

```
/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py:150: UserWarning: optimizer.eps is changed to 1e-08 by MultiprocessParallelUpdater for new batch size.
  format(optimizer.eps))
Exception in main training loop: list index out of range
Traceback (most recent call last):
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 231, in update_core
    loss = _calc_loss(self._master, batch)
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 262, in _calc_loss
    return model(*in_arrays)
  File "/home/rezha/dataloka/see/chainer/utils/multi_accuracy_classifier.py", line 45, in __call__
    self.loss = self.lossfun(self.y, t)
  File "/home/rezha/dataloka/see/chainer/metrics/loss_metrics.py", line 211, in calc_loss
    overall_loss_weight = loss_weights[i - 1]
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train_fsns.py", line 292, in <module>
    trainer.run()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 231, in update_core
    loss = _calc_loss(self._master, batch)
  File "/home/rezha/miniconda3/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 262, in _calc_loss
    return model(*in_arrays)
  File "/home/rezha/dataloka/see/chainer/utils/multi_accuracy_classifier.py", line 45, in __call__
    self.loss = self.lossfun(self.y, t)
  File "/home/rezha/dataloka/see/chainer/metrics/loss_metrics.py", line 211, in calc_loss
    overall_loss_weight = loss_weights[i - 1]
IndexError: list index out of range
```

What happen?

**Comment by rezha130** [comment]
Hi @mit456  thanks for helping

Yes, previois` IndexError: list index out of range` in `calc_loss` happen when i am using this ground truth file based on FSNS style

```
6	22
mytrain/images/01179.jpg	18	31	43	31	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	23	25	22	13	29	5	18	24	19	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
```

Is there any maximum limitation of `times step` & `num_labels ` in using FSNS-like experiment?

**Comment by rezha130** [comment]
@Bartzi 

Can i used my custom `my_char_map.json` for FSNS-like train in my custom train data set?Or i must used `fsns_char_map.json` which already provided in my custom train?

**Comment by Bartzi** [comment]
@rezha130 Before you resized your images to `600x150`, did you check that they have the same semantics as the images of the FSNS dataset? **This is important!!**

Forget about the `loss_weights` in `loss_metrics.py` they are not useful for your training. I just used them to make it possible to put some emphasis on certain timesteps of the optimization.
Technically there is no limit for `num_timesteps` and `num_labels`. You can of course use your custom `char_map`, but you will need to adapt [this line](https://github.com/Bartzi/see/blob/master/chainer/models/fsns_resnet.py#L28), and change the number of classes you want to distinguish.

**Comment by rezha130** [comment]
@Bartzi you're right. I forgot to check that neural net hyperparameter.

Now, train can run!

Can you please share another hyparameter that i need to adjust in FSNS neural net layers?

**Comment by rezha130** [comment]
@Bartzi if i want to use fixed lower image size? what should i change?

**Comment by rezha130** [comment]
![4d162df0-c59e-4f26-bf32-7c1656653931](https://user-images.githubusercontent.com/39994669/42268052-c8d525b0-7fa4-11e8-81c0-978db7e95653.png)

```
num_timesteps = 2
num_labels = 16
```

main/accuracy = 0.49 in 1700th iteration.

But something strange in bounding box result. Whats happen?

**Comment by Bartzi** [comment]
I told you to delete the `loss_weights`, this will fix your problem, but it still won't help you that much.

I ask again, did you have a look at the FSNS dataset? Did you see that there are always 4 views of the same street name sign that are shown at the same time? Your data does not have this property, so you can not use this script without modifications!
The fact that your predictions already look quite good, is in my point of view a hint that the network memorizes your data and your data has view variations making it easy for the recognition network to memorize (i.e. overfit)

**Comment by Bartzi** [comment]
First, you will need to change the network definition and the way predictions are made ([1](https://github.com/Bartzi/see/blob/master/chainer/models/fsns.py), [2](https://github.com/Bartzi/see/blob/master/chainer/models/fsns_resnet.py).
You will also need to change the way metrics/loss are calculated ([1](https://github.com/Bartzi/see/blob/master/chainer/metrics/loss_metrics.py), [2](https://github.com/Bartzi/see/blob/master/chainer/metrics/softmax_metrics.py)). Furhtermore, you will need to think about, whether you want to use curriculum learning or not, and if you want to plot the current state of the network for each iteration (if you want to do this you might need to make changes in the bbox plotter to, or look whether there is one that is already able to work with your way of making predictions and your way of training).

**Comment by rezha130** [comment]
OK @Bartzi  

That 4 py file that i will try to modify.

Now for bbox plotter: What script on your code if i just want train model on **SINGLE image** with max of 2 or 3 or more than 4 words? So i got plot like this (screenshot from your video), **NOT** 4 views of the same street name sign that are shown at the same time :

![09c7517d-d1f9-4507-b962-d2288ea3fff8](https://user-images.githubusercontent.com/39994669/42312738-4df3d4f0-806b-11e8-93f2-f03972de37e6.png)

**Comment by Bartzi** [comment]
Sounds good so far :sweat_smile:. You could have a look at all the bbox plotters [here](https://github.com/Bartzi/see/tree/master/chainer/insights), you will see that all special classes inherit from the class `BBOXPlotter`. A good example could be the SVHN BBOXPlotter.

**Comment by rezha130** [comment]
Hi @Bartzi 

If i try to set for `calc_loss`
`loss_weights = [1, 1.25, 2, 1.25, 1, 1.25, 2, 1.25, 1, 1.25, 2, 1.25, 1, 1.25, 2, 1.25]`

just specific for my longest custom training dataset with max `num_timesteps = 16`. Am i correct?

And one more thing, would you please explain what is different objective of `image_size` & `target_shape` in your `train` ? I set it with same value and then use it for resizing image

```
image_size = Size(width=200, height=40)
target_shape = Size(width=200, height=40)

attributes_to_adjust = [
        ('num_timesteps', ['predictor', 'localization_net']),
        ('num_timesteps', ['predictor', 'recognition_net']),
        ('num_timesteps', ['lossfun', '__self__']),
        ('num_labels', ['predictor', 'recognition_net']),
    ]

 curriculum = BabyStepCurriculum(
        args.dataset_specification,
        FileBasedDataset,
        args.blank_label,
        attributes_to_adjust=attributes_to_adjust,
        trigger=(args.test_interval, 'iteration'),
        min_delta=0.1,
    )

    train_dataset, validation_dataset = curriculum.load_dataset(0)
    train_dataset.resize_size = image_size
    validation_dataset.resize_size = image_size
```

**Comment by Bartzi** [comment]
I suggest, that you just delete `loss_weights` from the code, they might come in handy if you need to get mroe accuracy out of the model.

The difference between `image_size` and `target_shape` is the following:
- `image_size`: this is the size of the input image for the localization network
- `target_shape`: this is the size of the input image for the recognition network

I hope this also answers your question, why at one place one value is used and somewhere 
else another value. So it is not advisable to set them to the same value.

**Comment by rezha130** [comment]
@Bartzi now i can train with variety of my custom data set after do modifications in train & inference script, no error. But still the result not good as expected. As example on this bbox image evaluation form last epoch:

![01718a94-97a9-48ba-b447-e2488ed5ed00](https://user-images.githubusercontent.com/39994669/42684259-c35245b6-86b9-11e8-9747-370881228786.png)

log also look impressive:
```
{
        "main/loss": 0.28168749809265137,
        "main/accuracy": 0.9703125,
        "validation/main/loss": 0.25905805826187134,
        "validation/main/accuracy": 0.9751243781094526,
        "lr": 9.999999999987483e-05,
        "epoch": 400,
        "iteration": 26700,
        "elapsed_time": 50062.12740638801
    }
```
but when i try inference on same image above, i got recognition result: `NIK 3175610990006` which is different from bbox result. Please help me on this.

And also, how can i set `target_shape` for recognition network input. As example, i set this network input size for image above
```
image_size = Size(width=200, height=40)
target_shape = Size(width=140, height=30)
```
`timestep = 2`because i want 2 bbox for left sentence and right numeric sequence.
Please correct me if i'm wrong.

**Comment by rezha130** [comment]
Hi @Bartzi , would you please give some comments for my issue above?

Kindly Regards

**Comment by Bartzi** [comment]
I think its working very well for you because your dataset is too easy. You said tghat each transcription starts with the same characters `NIK`. It is verye asy for the network to memorize this, hence it does not need to locate these characters in order to predict them correctly.
The same could be true for your numbers, I think if you'd increase the number of train images and add more variety, the network won't be able to memorize the numbers, just based on some easy features that have been extracted by the network. You could also try to decrease the capacity of your network (i.e. use a network with less parameters).

For your inference problem:
Did you check whether the network predicts the correct number of labels, while the blank tokens are not stripped out, yet?

Your `target_shape` looks good. NUmber of timesteps also seems to be reasonable.

**Comment by rezha130** [comment]
Thanks @Bartzi . I checked again my inference script. I found that there is a mistake on me. Now, i got 16 character result in inference.

But i still curious, how i can draw BBox image correctly for evaluation purpose?

**Comment by Bartzi** [comment]
As I said, the problem is, that the network is able to memorize all data based on easy to extract features, that's why your network does not learn to localize the characters because it is lazy and does not need to. Think of a human that can do a task very easily, but does not it the way you, still he succeeds, you'll likely have to make the task harder for him!

I think that this is the reason, why the BBoxes are not on the characters.

**Comment by rezha130** [comment]
@Bartzi 

Maybe network is relatively easy to memorize `NIK` word, but i don't think with next sequence of numeric characters. The train data set is 1300 images (is it enough?), where every image is unique value of sequence number. Those images is ID number, where there're no duplicate ID number value in every record of ground truth file.

**Comment by Bartzi** [comment]
If you take a closer look at the network architecture of SEE, you will see (no pun intended^^) that the network will only achieve good results if, and only if the localization network is able to provide enough information for the recognition network to succeed.

Now take a closer look at the image you provided some posts ago. We can see that the localization network did not localize `NIK` (the blue bbox), because everythin starts with `NIK`, very easy for the network to learn. The second localization spans some of the numbers, it seems that this information is enough for the network to correctly identify the rest of the number sequence. This shows us that the task is too easy for the network, mostly because your training set is not large enough (did you try to generate similar looking images with unique sequences?) or the network as such has too many parameters and hence the network is highly overfitting to your data.
