### ISSUE TITLE
Unable able to Train (SVHN and FSNS)  

### ISSUE THREAD

**Issue by Devadattaprasad** [Bartzi/see#51]
Hi Bartzi,

I want to run the **train_svhn.py**,
I have prepared the data set as per the instruction given in **Read me** file for running **train_svhn.py**.
As per #20 , because of alignment  issue in **gt file** , training is not running. I made necessary changes in the gt file shown below ![here ](https://user-images.githubusercontent.com/42034076/45887873-54eae300-bdda-11e8-98b2-cff6461a8744.png)

I tried with train both the train_svhn.py and train_fsns.py, It remain in 1st iteration ( screenshot for reference) ![screenshot ](https://user-images.githubusercontent.com/42034076/45888048-ba3ed400-bdda-11e8-8745-265b9e75c59f.png)

I am not able to understanding, Why training is not continuing.

Argument list for reference
![image](https://user-images.githubusercontent.com/42034076/45888238-35a08580-bddb-11e8-81c4-252790c3e5c7.png)

Kindly help me to resolve the issue.
Thanks in advance

**Comment by Bartzi** [comment]
I think I now what the problem is. You can try to change [this](https://github.com/Bartzi/see/blob/master/chainer/train_svhn.py#L143) and the following line to use [MultiThreadIterator](https://docs.chainer.org/en/stable/reference/generated/chainer.iterators.MultithreadIterator.html#chainer.iterators.MultithreadIterator) or [SerialIterator](https://docs.chainer.org/en/stable/reference/generated/chainer.iterators.SerialIterator.html#chainer.iterators.SerialIterator).

I also had this problem on some machines and datasets, something seems not to be right in the interprocess communication.

**Comment by Devadattaprasad** [comment]
@Bartzi , Thank You. After changing code **"chainer.iterators.MultiprocessIterator"** to '**chainer.iterators.MultithreadIterator**' , above issue got resolved.

I want prepare my own character map.
Kindly let me know the process of creating my own **"character_map"**. 

Thank you in advance. :-)

**Comment by Bartzi** [comment]
Creating a new character_map is actually quite easy. Have a look at [this  comment](https://github.com/Bartzi/see/issues/6#issuecomment-372953800). There I explain the idea behind the char map.
This should give you all information you need to create a char map on your own =)

**Comment by Devadattaprasad** [comment]
Thank you, Bartzi, for quick reply.

I have few doubt, 
When, I am running a evaluation for **fsns**.

1. What is the reason for defining **TimeStamp**, 
As per my understanding, **TimeStamp** variable  is used  to define how many words need to predict. "say  **TimeStamp = 1**  it will predict 1 work  and so on". Please correct me,If I am wrong. 
Below image, ran the evaluation code with parameters as shown below.
![image](https://user-images.githubusercontent.com/42034076/46075531-5d5f6700-c1a8-11e8-97e1-70bb8768e6b6.png)

Expected Result 4 bounding box and the predicted word.
![image](https://user-images.githubusercontent.com/42034076/46075329-c5fa1400-c1a7-11e8-9277-21351641f2a9.png)

But I got 4 bounding box, for 3 box drawn on words and 1 bounding box is overlapping on 3rd box.
Predicted 3 words. But as there are more than 3 words are in the image.
 
2. What is the reason for limiting **TimeStamp** between 1 to 6, if I define **TimeStamp** with value more the 6 it will throw error as shown below
![image](https://user-images.githubusercontent.com/42034076/46076470-440bea00-c1ab-11e8-9dd6-fafe0dbe23cd.png)

3.  I want to understand ,weather localization  will be done for complete image or in specific part of the image.
As in the above result. There are more that 3 words, but it only  predicted 3 words, which are in specific part and ignored remaining words
 
4. Assume, In real word scenario. we do not know how many words in the scene, How will you counter such scenarios.

5. What if the Scene does not have any text at all.

Please correct me, if my understanding is wrong.

**Comment by harshalcse** [comment]
@Devadattaprasad 
I'm tring to train SVHN dataset using following train.csv which path is defined in curricum.json as follows 
![train](https://user-images.githubusercontent.com/5838252/54102268-b71dbb80-43ed-11e9-8629-1e3be6c38b83.PNG)
Command for trainning svhn dataset is 
sudo python3 chainer/train_svhn.py 
"/root/see-master/datasets/train_dataextract_train/curriculum.json" 0 
--char-map /root/see-master/datasets/svhn/svhn_char_map.json 
--test-image /root/see-master/datasets/test_dataextract/train/0.png 
-b 60

but getting error as follows:
Traceback (most recent call last):
  File "chainer/train_svhn.py", line 75, in <module>
    train_dataset, validation_dataset = curriculum.load_dataset(0)
  File "/root/see-master/chainer/utils/baby_step_curriculum.py", line 38, in load_dataset
    train_dataset = self.dataset_class(self.train_curriculum[level], **self.dataset_args)
  File "/root/see-master/chainer/datasets/file_dataset.py", line 31, in __init__
    self.num_timesteps, self.num_labels = (int(i) for i in next(reader))
  File "/root/see-master/chainer/datasets/file_dataset.py", line 31, in <genexpr>
    self.num_timesteps, self.num_labels = (int(i) for i in next(reader))
ValueError: invalid literal for int() with base 10: '/root/see-master/datasets/train_dataextract_train/train/0.png'

Request you to help me to resolve the issue.
